version: '3.8'

services:
  qt-designer-vnc:
    build: .
    user: "${USER_ID}:${GROUP_ID}"
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - RESOLUTION=${RESOLUTION}
    ports:
      - "127.0.0.1:5900:5900"
    tty: true
